### ISSUE TITLE
multiple trade in single request

### ISSUE THREAD

**Issue by saadamin** [jaggedsoft/php-binance-api#148]
**Title**
multiple trade in single request

  
**Platform:**
- windows 10

**php version:**
- 7.0.24

**Long description**
$api->marketBuy() executed 2 single trade in fraction , the amount/quantity was 9 , its really strange 2 trades occurred . 

![image](https://user-images.githubusercontent.com/4682435/39961308-0235b474-5655-11e8-8239-56a4abe80fc3.png)

I have tried second time again with 9 quantity . and this time it was a single trade.
![image](https://user-images.githubusercontent.com/4682435/39961334-99ad6a72-5655-11e8-933c-4ac79bf9e3d5.png)

the screenshots are from binance Trade History page.
 
it will be very difficult to update user balance if it keep happening like this . 

Any idea why this happened ?

**code**
```php
$order = $api->marketBuy('AEBTC', 9);
```

```

thank you

**Comment by dmzoneill** [comment]
this is expected behavior, its how all trading works on all platforms.

at the time you requested 9 time there was only 2.61 available at 0.0004578.
There were no more available at this price.  to complete your order the system filled it at the next available price on sale 0.0004584.

on the next occasion you did it there were 9 available for purchase at this price.

same works for limit orders, and why you have have 'partially filled' orders.  The differnece with limit orders is it will wait to buy at given price.  Market will buy at whatever price is available.

if you were to buy 100 you could potentially end up buying, e.g

10 @ $1
10 @ $2
10 @ $3 
......

**Comment by saadamin** [comment]
so how to trace $trade variable? does is return every trade or the last trade?
$trade =$api->marketBuy() ;

**Comment by jaggedsoft** [comment]
I can confirm this is expected behavior. You can pass the `newOrderRespType` to get a list of all your fills. Then you can determine your cost average if necessary. I just use the price of the very last fill

```
$order = marketBuy('BNBBTC', 1, ["newOrderRespType"=>"FULL"]);
print_r($order);
```

**Comment by saadamin** [comment]
Thanks @jaggedsoft  , really appreciated your help.
