### ISSUE TITLE
Why is this PHP API downloading "ca.pem" and storing it in every single directory on my web server? (I already have an SSL cert)

### ISSUE THREAD

**Issue by GalacticSun** [jaggedsoft/php-binance-api#166]
**Title**
- Why is this PHP API downloading "ca.pem" and storing it in every single directory on my web server? (I already have an SSL cert).

**Short Description:**
- I'm guessing this has something to do with the Binance API requiring SSL / having a cert, in which case that is good this PHP API is downloading one automatically for us - but, what if we already have one?  Why is it necessary for this PHP API to download this "ca.pem"?  Can I turn this off, please?

- The reason I ask is because it requires my web directories to be more insecure than I'd like (I have to set them to 775 so PHP can write to the folder).  Also, when trying to set up an API call as a PHP script as a Linux service it is erroring out, saying "/ folder is not writeable, plese check your permissions" (line 2130 of the PHP API).

- Can I disable this functionality of downloading the "ca.pem" file, please?
  
**Platform:**
- linux

**php version:**
- 7.1.12

thank you

**Comment by dmzoneill** [comment]
Hi,

We download the ca.pem from curl website because they're are many users using wamp and other packaged (wamps).  These bundles have outdated ca.bundles. failing the certificate authority verification

The ca.pem is written relatively to the callin script.

Sounds like you have many scripts in different folders including the php-binance-api.php, in each folder then an ca.pem is appearing.

If you feel like doing so.  You can immediately right now make it an absolute url, such that only file will be created at a location of your chosing.

Ill give a think about best way to do this in windows and linux.  

Getenv ("home") . "/ca.pem", might be the best option

Thanks for your valuable feedback

**Comment by GalacticSun** [comment]
Hi there,

Thanks very much for the quick reply.  Ok, sure, I can change it to be an absolute path, that works fine.

Will there be an option in the future to maybe use our own cert?  I'm guessing if we have a server with our own SSL/TLS cert where the request is coming from then we don't need this ca.pem functionality in the PHP API, correct?

Much appreciated and keep up the great work!

**Comment by dmzoneill** [comment]
I will add an option.. thanks for the feedback

**Comment by GalacticSun** [comment]
Great!  Thanks :)
You guys really have built a great project here, it is really solid and full featured, yet simple.  And your responsiveness is fantastic.  Just wanted to let you guys know.

**Comment by dmzoneill** [comment]
im closing this now

@jaggedsoft 
@GalacticSun 

https://github.com/jaggedsoft/php-binance-api/commit/07e7b8c90c29d120f1c44ace152ed732a16da057

```
$api = new Binance\API( "somefile.json" );
$api->caOverride = true;
```

**Comment by jaggedsoft** [comment]
<3

**Comment by OscarEriksen** [comment]
Thanks for the above fix, @dmzoneill and @jaggedsoft.

I'd suggest re-opening this and allowing for a more robust fix in terms of setting the path to download the .pem-file. Also to give my 2cents I don't think code that is added in order to satisfy "WAMP" should be in this library.

Using this with composer, Laravel & Laravel Forge with the latter seemingly being the culprit here. Tries to write to /ca.pem which is wrong in so many cases.

BR
oe
