### ISSUE TITLE
New response from /api/v3/order

### ISSUE THREAD

**Issue by Marc008** [jaggedsoft/php-binance-api#175]
Hello, 

I don't know if it always has been in this way but it looks like the recent update from Binance, now responds with ACK, RESULT or FULL.

For 2 days ago, I'm getting the ACK response by default, before, I got he RESULT response.

Is there any way to specify the response that you want to get?

Thanks!

**Comment by jaggedsoft** [comment]
When doing market buys you can set `newOrderRespType` to `FULL` in order to get the complete response of order fills, like this:
```php
$order = marketBuy('BNBBTC', 1, ["newOrderRespType"=>"FULL"]);
print_r($order);
```

This returns an array of `fills` which includes `price, qty, commission, commissionAsset, and tradeId`
![39147371-5499f73a-4731-11e8-90b5-089340a83ddc](https://user-images.githubusercontent.com/4283360/41242714-1eee7292-6d55-11e8-8801-35ab1c32f7b2.png)

This does not apply to limit orders however

**Comment by Marc008** [comment]
But just 2 days ago, by default this is the response that I got:

> Array
> (
>     [symbol] => BNBBTC
>     [orderId] => XXXXXX
>     [clientOrderId] => YYYYYYYYYY
>     [transactTime] => 1509870230894
>     [price] => 0.00239810
>     [origQty] => 0.63000000
>     [executedQty] => 0.63000000
>     [status] => FILLED
>     [timeInForce] => GTC
>     [type] => LIMIT
>     [side] => BUY
> )
> 

Is there any way to get that response (I think it's the RESULT option) for limit orders?

**Comment by BenBao93** [comment]
@Marc008 well LIMIT orders are not necessarily filled when placed so much if the data in the full response simple isn't there yet when you create the order initially.
