### ISSUE TITLE
Question : calculate lot size for quantity order

### ISSUE THREAD

**Issue by andibastian** [jaggedsoft/php-binance-api#187]
Hai, how to calculate Lotsize ? . Sometime result error like this :
"Filter failure: LOT_SIZE"

For now, i'm using this way to calculate :

Format i used :
> function btc_format($value){
    $value = sprintf('%.8f', $value);
    $value = rtrim($value, '0');
    return $value;
}

> $saldo_buy=($saldo/100) * 50;`
$quantity=$saldo_buy;
$price=btc_format($price);
$order = $api->buy("$kode"."$pair", $quantity, $price);

The result is, sometime good, sometime error : Filter failure: LOT_SIZE"

How to the best way calculate LOT_SIZE ?

**Comment by jaggedsoft** [comment]
Generally this is due to a few different things:
Need to clamp order quantity to minQty
Need to clamp order value to a minimum of minNotional. minimum order value (price * quantity) see the picture at the bottom of this page.
Need to format the number of decimals properly like below
```php
$sellPrice = number_format($sellPrice, 8, '.', '');
$orderSell = $api->sell('MFTBTC', $notes['quantity'], $sellPrice);
```
----------

You can use `$api->exchangeInfo();` to pull the minimums for each pair
![example](https://image.ibb.co/bz5KAG/notationals.png)

todo: implement tickSize handling and roundStep like node-binance-api:
#121


@ahab1b here is a script someone made to make it easier on php

https://github.com/jaggedsoft/node-binance-api/issues/23#issuecomment-383795797

```php
$info = $api->exchangeInfo();
$minimums = [];
foreach($info["symbols"] as $symbols){
$filters = ["minNotional"   => "0.001","minQty" => "1","maxQty" => "10000000","stepSize"   => "1","minPrice" => "0.00000001","maxPrice"   => "100000"];
$filters["orderTypes"] = implode(",",$symbols["orderTypes"]);
	foreach($symbols["filters"] as $filter){
		if ( $filter["filterType"] == "MIN_NOTIONAL" ) {
				$filters["minNotional"] = $filter["minNotional"];
			} else if ( $filter["filterType"] == "PRICE_FILTER" ) {
				$filters["minPrice"] = $filter["minPrice"];
				$filters["maxPrice"] = $filter["maxPrice"];
			} else if ( $filter["filterType"] == "LOT_SIZE" ) {
				$filters["minQty"] = $filter["minQty"];
				$filters["maxQty"] = $filter["maxQty"];
				$filters["stepSize"] = $filter["stepSize"];
			}
		}
$minimums[$symbols["symbol"]] = $filters;
}
$fp = fopen('exchangeinfo.json', 'w');
fwrite($fp, json_encode($minimums));
fclose($fp);
```

**Comment by andibastian** [comment]
okay, i'll try,  i will inform you soon.. thank you

**Comment by andibastian** [comment]
thankyou @jaggedsoft , solved
