### ISSUE TITLE
Very slow compared to Node.js lib

### ISSUE THREAD

**Issue by Aquive** [jaggedsoft/php-binance-api#23]
I don't know if this is a real issue or not, but I don't know where to put it. Is this lib (very) slow compared to the Node.js API lib located here https://github.com/jaggedsoft/node-binance-api

I am trying to do analysis where every part of a second counts. To make it clear, my questions is; is this library suitable for this? Or should I move to another solution? I don't know what makes it slow. Are the endpoints just slow or can I do something on my side to make if faster?

**Comment by webqap** [comment]
What exactly do you find slower?

**Comment by Aquive** [comment]
Fetching rates for symbols. I am using `$this->api->prices();`. It fetches all prices. Is there a way to fetch just the symbols I want? Is this maybee documented somewhere?

**Comment by jaggedsoft** [comment]
This library is very fast for me. What version of PHP are you using?
We are using file_get_contents for all of our http requests, in order to maximize compatability and reduce dependencies. But we may offer a version with alternative methods, such as cURL.

I personally prefer the node library myself. It has a lot more testing and the development is ahead by many hours or weeks
