### ISSUE TITLE
User Data: Account Balance Updates, Trade Updates, New Orders, Filled Orders, Cancelled Orders via WebSocket

### ISSUE THREAD

**Issue by mrsantran** [jaggedsoft/php-binance-api#30]
This function not work.

![screen shot 2018-01-17 at 5 06 21 pm](https://user-images.githubusercontent.com/21286108/35037049-d585ca24-fba8-11e7-9460-b36797ee3236.png)

**Comment by jaggedsoft** [comment]
I'll check it out, i've got limited availability this week but i will try

**Comment by elmondogri** [comment]
I have the same error while using trades function (aggTrade), after about 10 minutes the connection closes with 1006 error and php notice for undefined symbol.

It used to work a few days ago, do you know what s happening?
![image](https://user-images.githubusercontent.com/20752444/35069801-f98997f8-fbe3-11e7-8cba-bf157d52b1cc.png)

**Comment by jaggedsoft** [comment]
I am not sure. Binance is changing things faster than I can keep up, only now they are not notifying us of changes

**Comment by elmondogri** [comment]
I understand, please let us know if you find something, anyway this api is useful and having it to work serverside is way better for data manipulation and backup, thank you for sharing your work with us!

**Comment by carllewis1980** [comment]
Hi - Firstly thanks for all the hard wok you put into this Jaggedsoft.

Anyone got this working yet?

**Comment by hhrealestatemedia** [comment]
hey man, ya, I'm trying to just fetch something and its returning an empty array. any idea when you might have a working example? I do see from cointracking.info that they are saying binance's api is unusable right now? weird. Do you know what they're doing or when they might make it usable? thanks for putting all this together. we all appreciate it. Justin

**Comment by carllewis1980** [comment]
My streams are working...?!?

**Comment by hhrealestatemedia** [comment]
oh ya? wierd. I couldn't get anything to work as is. I just now got it going by adding this to the php-binance-api.php...
`		$opt = [
			"http" => [
				"method" => $method,
				"ignore_errors" => true,
				"header" => "User-Agent: Mozilla/4.0 (compatible; PHP Binance API)\r\n"
			],
			"ssl" => [
					"verify_peer"=>false,
					"verify_peer_name"=>false,
			]`

because i kept getting: Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Now I'm able to get the contents just fine. I know it isn't as secure but is it that important? I'm guess that has to do with my own ssl cert? Right now I'm just testing on a codeanywhere stack. Maybe that is it.

**Comment by jaggedsoft** [comment]
Todo: add error reporting
