### ISSUE TITLE
Is there any endpoint to make deposit a fund on an account?

### ISSUE THREAD

**Issue by speroamey** [jaggedsoft/php-binance-api#334]
**Title**
- bug: XYZ broken
- feature: please add
- enhancement: add this to existing features

**Short Description:**
- Unable to get a result from blah
  
**Platform:**
- windows
- linux
- macos

**php version:**
- 7.0.24

**Long descrption**
- Doing xyz results in ypr and failing when fph

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API("<api key>","<secret>");
$ticker = $api->prices();
print_r($ticker); // List prices of all symbols
echo "Price of BNB: {$ticker['BNBBTC']} BTC";
```

**result**
```
{
   "result":"result"
}
```

thank you

**Comment by dmzoneill** [comment]
Hi Speroamey,

I'm sorry but you will need to expand on the question and how it is related to this project.

The api is defined here.
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md

In order to deposit you send(withdraw) from the source e.g. coinbase to a given address in binance.
In that case you are probably looking for coinbase API and the associated withdraw function..

If you want to withdraw in binance, this API only supports trading.

If you want to make a pull request to support withdrawals.
that would be great.

**Comment by speroamey** [comment]
Thanks @dmzoneill  for your quick reply. Eg:  suppose I have money on my credit card and I want to deposit it in my binance account, is it possible to do it via the API since it is possible via the binance interface.

**Comment by dmzoneill** [comment]
@speroamey 

The api is defined here:
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md

I don't see anything related to credit card purchases.
