### ISSUE TITLE
Unable to connect to multiple websockets

### ISSUE THREAD

**Issue by GavChap** [jaggedsoft/php-binance-api#351]
**Title**
- bug: Unable to connect to multiple websockets

**Short Description:**
- Unable to connect to multiple websockets
  
**Platform:**
- linux

**php version:**
- 7.4

**Long descrption**
I'm trying to connect to two websockets at the same time in the same thread in order to use callbacks to get both userData and a ticker. Only the first one created will ever run, no matter which combination of websocket calls you use.

According to the PHP React documents you can run multiple websockets, but they all have to use the same loop. php-binance-api creates multiple loops meaning only the last one run works.

**code**
```php
        $this->api->ticker("BTCUSDT", function (API $api, string $symbol, array $tickerArray) {
            print_r($tickerArray);
        });

        $this->api->miniTicker( function ( $api, $ticker ) use ( &$count ) {
            print_r( $ticker );
            $count++;
            print $count . "\n";
            if($count > 2) {
                $endpoint = '@miniticker';
                $api->terminate( $endpoint );
            }
        });
```

**result**
Only the last one created works correctly.

**Comment by blondie101010** [comment]
> According to the PHP React documents you can run multiple websockets, but they all have to use the same loop. php-binance-api creates multiple loops meaning only the last one run works.

I just verified the code and it uses a single loop.  

Do note that the loop control is done in the library, not in your own code.  So if you look at React documentation, you have to apply it to the php-binance-api package source code.

Moving the loop out of there would make the whole library less usable

> Only the last one created works correctly.

That only makes sense if the first call fails considering the `ticker()` and `miniTicker()` are locking calls.

**Comment by GavChap** [comment]
That's the problem, both ticker and miniticker use their own loops as they use the Create function. You can't have both userInfo and ticker running from the same thread. I've tried it both ways. Each of the websockets start the loop, once you've started the loop, you can't add more sockets INTO the same loop when it's running.

**Comment by blondie101010** [comment]
So you basically want to take the loop control out of the library.

This implies that you'd have to get the loop set up and started from your application code.  In order to avoid a breaking change, there are a couple of options:

- Add parameters and properties so that the existing methods could optionally use a customized loop.  This would require changing all existing WebSockets methods, and therefore imply a considerable maintenance cost.
- Copy all the relevant WS methods to new names and adapt them to support an hybrid loop control.  Like the previous case except methods are not changed, new ones are added instead.  This would probably be slightly better for the code quality and maintenance cost, but still not negligible.
- Do your own implementation of what you want, using the provided API controls from your application code.  This implies defining the loop in your own code, and is definitely the solution which seems most appropriate to me.  If you want to handle 2-3 specific streams in the loop, you just do them, possibly copy-pasting existing code from the library.

A word of caution: Binance's limit controls have been getting quite harsh, so you have to carefully limit your interactions with their API to a minimum.

**Comment by GavChap** [comment]
I actually went with option 3 and implemented my own websocket code and only use the PHP SDK to do balance checks and buys/sells.

I thought about the 2nd option and doing a pull request, but I don't have the time right now to do that.

Thanks for your help though.
