### ISSUE TITLE
WebSocket API returning error

### ISSUE THREAD

**Issue by Penn0r** [jaggedsoft/php-binance-api#51]
Hi,
I'm getting an error when trying to use the WebSocket example:

$api->chart(["BNBBTC"], "15m", function($api, $symbol, $chart) {
    echo "{$symbol} chart update\n";
    print_r($chart);
});

**Notice: Undefined variable: symbol in php-binance-api.php on line 619**

**Notice: Undefined variable: interval in php-binance-api.php on line 619
chart(,)) Could not connect: DNS query for stream.binance.com failed: too many retries**

**Comment by jaggedsoft** [comment]
That's strange, those are nowhere near line 619 in the current version
Sure you're using the latest version?

**Comment by Penn0r** [comment]
I have just checked and there are 703 lines in php-binance-api.php
https://github.com/jaggedsoft/php-binance-api/blob/master/php-binance-api.php

Am I using the wrong file?

**Comment by jaggedsoft** [comment]
That's the same one I'm using
I'm not sure what exactly is going wrong here, but possibly something from composer

try running this from your project directory:
```
composer require ratchet/pawl
```

There may be something in your environment preventing this from running, not sure what since no one has reported this before. Worst case scenario you can deploy this on a $5 VPS such as digitalocean, vultr, etc. Should work out of the box
I use debian linux, seems to be the easiest

**Comment by Penn0r** [comment]
Hi Jon,

Here is the response from that command:

bash-3.2$ ./composer.phar require ratchet/pawl
Content-type: text/html

Warning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI
Using version ^0.3.1 for ratchet/pawl
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
bash-3.2$

**Comment by jaggedsoft** [comment]
Unfortunately something is different about your environment and I am not sure how to help you get composer going
But composer is definitely required for this to work
