### ISSUE TITLE
Missing test orders

### ISSUE THREAD

**Issue by fabiomlferreira** [jaggedsoft/php-binance-api#58]
There are any endpoints to create test orders with the api installed via composer. 

I think it's very important to create a test order endpoint

**Comment by jaggedsoft** [comment]
Yes, I am aware of numerous improvements that can be done to the library, I really want to do them all, but I need to enlist the community's help because I am very busy this month and short on time

Maintaining the node js version (17k downloads vs 3k) is the priority for now and it takes up all my time
https://github.com/jaggedsoft/node-binance-api/

**Comment by dmzoneill** [comment]
my pull request can close this issue
https://github.com/jaggedsoft/php-binance-api/pull/65
