### ISSUE TITLE
Can do request, but can't place any orders, no output

### ISSUE THREAD

**Issue by wesly1988** [jaggedsoft/php-binance-api#84]
Hi guys,

Love the API. 
Doing request works great for me, but somehow when I place an order, it doesn't do anything. 

`$api = new Binance\API(
"***",
"***",
['useServerTime'=>true]
);

//Call this before running any functions
$api->useServerTime();

// Place a MARKET order
$quantity = 1;
$order = $api->buy("BNBUSDT", $quantity, 0, "MARKET");
print_r($order);`

What am I doing wrong here any suggestions? 
While placing an order, it doesn't show any errors, but it also doesn't show any outputs. 

Thank you.

**Comment by wesly1988** [comment]
I know the min order is 10 usd, but when I also put 2 BNB or three it still doesn't do anything. Tried it with several ico's. Looks like the Api doesnt place any others at all.

**Comment by dmzoneill** [comment]
as of 30 seconds ago

dave@dave-laptop:~/Desktop/php-binance-api/examples$ cat orders_one.php 
<?php

require '../php-binance-api.php';

// @see home_directory_config.php
// use config from ~/.confg/jaggedsoft/php-binance-api.json
$api = new Binance\API();

// Place a MARKET order
$quantity = 1;
$order = $api->buy("BNBBTC", $quantity, 0, "MARKET");
print_r($order);


dave@dave-laptop:~/Desktop/php-binance-api/examples$ php orders_one.php 
Array
(
    [symbol] => BNBBTC
    [orderId] => 31748092
    [clientOrderId] => 0Eu41PZ4eUG80WYluZKRek
    [transactTime] => 1521467960631
    [price] => 0.00000000
    [origQty] => 1.00000000
    [executedQty] => 1.00000000
    [status] => FILLED
    [timeInForce] => GTC
    [type] => MARKET
    [side] => BUY
)

**Comment by jaggedsoft** [comment]
just fyi, you only need to use
`['useServerTime'=>true]` 
or
`$api->useServerTime();`

one or the other, not both :)
You can view the minimum order quantities with `exchangeInfo()`
Note: this is a different format than the way it comes
![image](https://user-images.githubusercontent.com/4283360/36249988-528054dc-11f1-11e8-90b8-c6002f2639f0.png)

I build an array of minNotional, minQty, and stepSize.
Unfortunately placing orders with binance is not easy because you have to clamp order amounts by those values. But doing market orders over .001 btc is usually pretty foolproof

**Comment by wesly1988** [comment]
Don't really know what went wrong. 
Spend yesterday three hours to try to fix the error. 

This morning it suddenly worked. 
Seems like there was something wrong on Binance end. 

It works. 
Thank you for the replies guys.
