### ISSUE TITLE
What format is openTime

### ISSUE THREAD

**Issue by ph3l1x** [jaggedsoft/php-binance-api#9]
I am trying to figure out what format is returned for $api->prevDay with openTime and closeTime.. It doesn't appear to be epoch...

**Comment by jaggedsoft** [comment]
Yeah it's epoch, same format as `new Date().getTime()`
Let me know if you need some examples

**Comment by ph3l1x** [comment]
If I take the returned openDate into an epoch converter online and it also shows a weird date.. I keep getting Tue, 19 Jan 2038 03:14:07 +0000 Am I doing something wrong?

**Comment by jaggedsoft** [comment]
Because javascript time adds 000 at the end to convert it into milliseconds. If you are pasting it into an epoch converter then you need to remove 3 digits at the end, because they accept seconds.

**Comment by ph3l1x** [comment]
This is the example I am given.. 2147483647
There are no trailing zeros.. I am really confused.. What code do you use to get this to time format.. sorry if I am being annoying.

**Comment by jaggedsoft** [comment]
You are not being annoying, but I am not the one to teach you about how javascript time works, unfortunately I am too busy. I am sure there are places you can learn, it's not too tremendously difficult it just takes some getting used to
This is the best I can do

So if you take the response from `openTime` or `closeTime`
You get a value like `1513748112775`
This is the number of milliseconds since epoch
You can see what time this number equals by running this in your browser console: `new Date(1513748112775).toLocaleString()` which will give you the time `"12/19/2017, 9:35:12 PM"`
Now if you want to paste that value into an epoch time converter
Those time converters are told to use SECONDS not milliseconds
Javascript gives time in milliseconds however
So you if your number is:
`1513748112775`
You would need to paste this in the epoch time converter:
`1513748112` just get rid of the last 3 digits, or divide by 1000 to get the seconds.

![image](https://user-images.githubusercontent.com/4283360/34242051-5a53355c-e5ce-11e7-85d1-492173bc76aa.png)

**Comment by ph3l1x** [comment]
ok got it! missed the millisecond part.. I should be able to handle this. Thank you!!
